### ISSUE TITLE
ごあいさつ

### ISSUE THREAD

**Issue by hitobb** [tsukky1337/test#1]
ひとばしらさんです、こんばんわ。

早速ですが、ミッション発動です。
Read.meを更新して、簡単に自己紹介を書いてみましょうｗ

またチェックに来ますね～

**Comment by tsukky1337** [comment]
ひとばしらさんこんにちわ！

早速Read.meを更新してみました♪
一から教えて頂いてありがとございますm(_ _)m

**Comment by hitobb** [comment]
OK
ミッションコンプリート！
クローズします。

**Comment by hitobb** [comment]
ユーザーによってCloseされた場合は、再オープンが可能です。

**Comment by hitobb** [comment]
再び、クローズします。
