### ISSUE TITLE
オーナーによるissueのクローズ

### ISSUE THREAD

**Issue by hitobb** [tsukky1337/test#2]
ひとばしらさんですおはようございます。
セカンドミッションです。

私がオープンした、このissueをクローズしてみてください。

よろしくお願いいたします。

**Comment by tsukky1337** [comment]
これで合ってるかな…？？？

**Comment by hitobb** [comment]
OKです。
ちなみにクローズ後でもコメントは記載できます。

**Comment by tsukky1337** [comment]
そうだったんですね！安心しました♪
(. . )φ~
