### ISSUE TITLE
自己紹介を改行してみましょう！

### ISSUE THREAD

**Issue by kaminuma** [tsukky1337/test#4]
改行してみやすくしてみましょう！

**Comment by tsukky1337** [comment]
神沼さんこんにちわ！
お題をありがとうございます(^^)
早速調べてやってみました！

**Comment by kaminuma** [comment]
お疲れ様です☆
クローズした後もissueコメントは確認できますので、参考までに。

**Comment by tsukky1337** [comment]
ありがとうございます(^^)
github楽しいですね！
