### ISSUE TITLE
Readme.md以外のファイルをアップロードしてみよう

### ISSUE THREAD

**Issue by hitobb** [tsukky1337/test#5]
さて、次のお題です。
Readme.md以外のファイルを、アップロードしてみましょう。
利用するツールはこちらです。

https://desktop.github.com/

使い方、いろいろ調べてみてね～
よろしくお願いします。

**Comment by tsukky1337** [comment]
こんばんわ！
気づくのが遅くなりすみません。
早速アップロードしてみました♪

**Comment by tsukky1337** [comment]
と、思いましたがExcelだと差分が見れないんですね。。
別途別のファイルでもアップロードしてみます。。。

**Comment by hitobb** [comment]
Excelがダウンロードできることを確認しました。
バイナリ形式でアップされていますね。

この機能を使えば、ファイルの受け渡しも簡単w

次は差分チェックやってみたいので、テキストファイル系をアップしてみてください。

**Comment by tsukky1337** [comment]
まずtextを新規で１つアップロードしてみました！

**Comment by hitobb** [comment]
文字化けしていたので、プルリクエスト（修正候補の提案）を送りました。
ご確認ください。

**Comment by tsukky1337** [comment]
おはようごございます！
文字化けに気づけていませんでした。ありがとうございます。
早速、プルリクエスト頂いた内容をマージ？してみました！

**Comment by hitobb** [comment]
という感じで、みんなで共同でプログラムや文章をメンテナンスしていけるんですよ。
マージは「取り込み」です。
もう1つプルリクエストするので、今度は却下してみてくださいね!!

**Comment by tsukky1337** [comment]
ありがとうございます！
かなり便利な仕組みですね♪
みんなで作業できると楽しそうです(^^)

もう１つのプルリクエストお待ちしています。

**Comment by hitobb** [comment]
先ほど上げました。
ご確認ください。

**Comment by tsukky1337** [comment]
却下にあたる選択肢が見当たらず、
マージをせずにクローズしてみましたが、これで合っていますでしょうか？？？

**Comment by hitobb** [comment]
OK、正解です。
ミッションクリアですね、お疲れさまでした。

**Comment by tsukky1337** [comment]
よかった～！
うっかりマージを押してしまわないよう注意が必要なんですね。
ありがとうございました♪
