### ISSUE TITLE
フォークの練習

### ISSUE THREAD

**Issue by hitobb** [tsukky1337/test#8]
次のミッションです。
先ほど私が実施したように、
ほかの人の作ったリポジトリに修正依頼をかける場合、
最初にフォークという作業を行う必要があります。

以下のリポジトリをフォークしてみてください。

https://github.com/BitzenyCoreDevelopers/bitzeny

出来たらコメントをお願いします。
クリックするボタンの位置が非常にわかりにくいので、しっかり調べてくださいね。

**Comment by tsukky1337** [comment]
こんばんわ。フォークをしてみました。
ご確認お願いいたしますm(_ _)m

**Comment by hitobb** [comment]
出来てます!
では、フォークしたbitzenyd（自分の陣地にあるもの）を削除してみましょう。

危険なオペレーションだから、しっかり調べてみてね。

**Comment by tsukky1337** [comment]
ごめんなさい、質問させてください。
「bitzenyd」とは具体的にどれの事でしょうか？
リポジトリ内でファイル名を検索をかけてもヒットせず。。。

**Comment by hitobb** [comment]
失礼。
bitzenyリポジトリそのものの削除がミッションです。

https://github.com/tsukky1337/bitzeny

そのものを削除してください。

**Comment by tsukky1337** [comment]
tsukky1337配下のbitzenyリポジトリを削除しました。
ご確認お願いしますm(_ _)m

**Comment by hitobb** [comment]
確認しました〜
クローズです。

次の課題が最終です。
今日はペース早くてお疲れかと思いますので、明日以降にissueを上げますね。

お疲れ様でした!

**Comment by tsukky1337** [comment]
資産をいじるのは中々緊張しますが、とてもわくわくしています(^^)
いつも貴重な時間をありがとうございます！
明日以降もよろしくお願いします。

**Comment by hitobb** [comment]
以降は雑談なので、聞き流してください。

体験して頂いたので理解できると思いますが、
自分が作ったリポジトリを誤って消してしまうと、
もう後戻りができません。
（例えば、https://github.com/tsukky1337/test/　を消してしまうと、
　今日までのトレーニング結果（issue)が全部吹き飛んでしまいます）

こういう事故を防ぐために、
BitzenyCoreDevelopersという「みんなで使えるファイル置き場」を用意して、
マスター管理を一元管理しています、というのがこのプロジェクトのやり方です。

他のプロジェクトだと、ほかのルールで運用しているかもですね。
（結局は趣味です）

以上、ご参考になれば。
